### ISSUE TITLE
Renaming theme object is causing issues...

### ISSUE THREAD

**Issue by didimedina** [system-ui/theme-ui#1001]
**Describe the bug**
I want to change the name of my theme object to something else, for example, `space` to `spacers`. Then in my components, I use `useThemeUI()` and assign padding values like `spacers.tightest` for example. For some reason when I do this and console.log the value it logs it correctly but the rendered value is way off. However, when I rename it to its suggested name in the theme object to `space` it works as expected. This is strange to me bec I'd assume according to system-ui's documentation that so long it gets a valid value the name is arbitrary.

Any insight on why this is happening? 

**To Reproduce**
1. Go to the theme object and rename `space` to `spacers`
2. Then create a component and use the `useThemeUI()` hook to access your theme values as so: `const { spacers } = useThemeUI()` 
3. Apply a value to a css property as so `{px: spacers.tightest}`
4. Value from theme object doesn't get through. 

**Expected behavior**
I expect the right value to be passed in which in my case is 8px and instead, I'm getting roughly 40

Ultimately, I guess I'm wondering if I could rename the theme values since our company has a diff naming convention or if that inherently will cause issues...

**Comment by hasparus** [comment]
Renaming the scales isn't not exactly supported.
You can attach other objects to the the theme, but `px` (i.e. `padding-left` and `padding-right`) always tries to read `theme.space`.

What does "tries to read" mean?
The logic goes somewhat like this: _if there is something under `value` in `relevantScale`, return it, otherwise return `value`_.
The scale is hardcoded for each property.

Take a look at [the docs on Theme Scales](https://theme-ui.com/theme-spec/#theme-scales) or at [the code](https://github.com/system-ui/theme-ui/blob/ea8346f823dc2f96e650f086692349b293f5bb8e/packages/css/src/index.ts#L61).

**Comment by jxnblk** [comment]
Theme UI follows a theme specification, so you cannot rename the default scale names. If you have a different (legacy??) format, you can create a transformer to convert to Theme UI's standard, hope that helps
