### ISSUE TITLE
`as` prop types on Box are not supported in TypeScript

### ISSUE THREAD

**Issue by matheusps** [system-ui/theme-ui#1124]
**Describe the bug**
While using typescript, the svg types are not recognized.

**To Reproduce**
1. Import the Box component
2. Use the `as` prop with value "svg"
3. Try to use any `<svg>` specific prop

**Expected behavior**
The types must extend the native svg ones.

**Screenshots**
<img width="927" alt="Screen Shot 2020-08-11 at 16 39 27" src="https://user-images.githubusercontent.com/6964311/89941624-aa5c5300-dbf1-11ea-91f5-5ee7bb2d94a5.png">

**Additional context**
[Sandbox Link](https://codesandbox.io/s/bug-box-svg-tsx-kpdo8)

**Comment by hasparus** [comment]
Thanks for the issue, @matheusps! 

This is a known limitation. It's quite tricky to get `as` prop with field correctly working on Box. Despite merging prop types with the props of components passed in `as` prop is supported in `Field`, we stopped at the simplest implementation with Box.

You can work around it with `jsx` pragma (which can be transpiled by TS) and `sx` prop on `svg`.
```tsx
/** @jsx jsx */
import { jsx } from 'theme-ui';

<svg width="1em" sx={styles} />
```

**Comment by matheusps** [comment]
Works like a charm. Thanks @hasparus! Should I close this issue?

**Comment by hasparus** [comment]
Let's keep it open for a while until we describe this limitation in the docs and release them.

**Comment by alexanderchan** [comment]
@hasparus material-ui seems to have the types down for this with their [`OverrideableComponent` type](https://github.com/mui-org/material-ui/blob/next/packages/material-ui/src/OverridableComponent.d.ts).  They use `component` instead of `as` but it works the same, passing both props and refs correctly.

I've extracted just the types so they can be played with and used with the `as` prop to see how it works:

https://codesandbox.io/s/fast-field-13wbu?file=/src/LinkExample.tsx

This isn't a fully functional example since it's still using their ambient types and doesn't actually render it.  However it's pretty close to being able to assign the type directly.
