### ISSUE TITLE
Color attribute doesn't get value from theme when using Gatsby

### ISSUE THREAD

**Issue by flaviolivolsi** [system-ui/theme-ui#1146]
**Expected behavior**

Given a rebass component using the `color` attribute, the color should get the value from the theme.

Text component:
```
<Text color="primary">Hello world</Text>
```

Theme:
```
export default {
  colors: {
    primary: "#5752ff",
  }
}
```

The outcome should be a text with color `#5752ff`. It works fine on projects created with create-react-app, but on Gatsby projects the value doesn't get transpiled, hence the CSS will show `color: primary`. This happens whether I use the plugin `gatsby-plugin-theme-ui` or not.

**How to reproduce**

I created two sandboxes, a [create-react-app project](https://codesandbox.io/s/create-react-app-theme-ui-color-t4exr) and a [Gatsby project](https://codesandbox.io/s/gatsby-theme-ui-color-r12n1).

**Comment by lachlanjc** [comment]
Hey @flaviolivolsi! We don't recommend using Rebass since Components got built into Theme UI last year. Just change your important from `rebass` to `theme-ui` to use the proper components.

Additionally, your CRA demo seemed to work as expected for me, with the text in blue.

@hasparus Let's close this as a discussion/support ticket
