### ISSUE TITLE
codesandbox starter

### ISSUE THREAD

**Issue by VinSpee** [system-ui/theme-ui#130]
Hi!

I spun up a [codesandbox starter for Theme UI](https://codesandbox.io/s/theme-ui-starter-nbxrd)

features:

- Theme UI and its dependencies
- imports the `base` theme
- example of using `Styled`
- uses `@emotion/babel-plugin-jsx-pragmatic` to insert the jsx pragma and point it at theme-ui
- uses `babel-plugin-emotion` for smartness

I mirrored the prettier settings from this project and tried to keep the sandbox free of my own opinions, but feel free to offer feedback, and if you like it, fork it and add it to the docs or readme - letting people get up and running quickly.

**Comment by jxnblk** [comment]
This looks great! This could be added to the `examples/` directory (which we could then link to CodeSandbox), if you're interested in opening a PR for that. The only change I'd suggest is to not use `@emotion/babel-plugin-jsx-pragmatic` and show an example using the JSX pragma comment instead, which only affects files where it's included rather than every file that Babel transpiles. This also *should* allow the Emotion plugin to work like it normally does in modules where theme-ui isn't being used

**Comment by VinSpee** [comment]
Yep, I can do that. I'm curious as to why? Is the goal to not hide anything? To be as clear as possible? Or to make it easy to jump in?

**Comment by jxnblk** [comment]
Using a pragma comment is way more explicit, and since this is fairly experimental, I think it's a better approach to not use the theme-ui create element function everywhere in a code base. Even with the `css` prop, I've seen people run into a lot of issues with Babel not being configured correctly to use the custom create element function, and I think it's an easier way to get started – if you're comfortable with the babel setup in your own application, by all means use it though.

**Comment by jxnblk** [comment]
I *think* we got this in, but feel free to reopen if not
