### ISSUE TITLE
sx prop giving typescript error when using a variable.

### ISSUE THREAD

**Issue by eddysims** [system-ui/theme-ui#1407]
**Describe the bug**

I have a component that is giving me a strange typescript error when using the `sx` prop.

If i do something like this:

```
 function Component() {
   const style = { textTransform: "uppercase" };
   return <div sx={style}>{children}</div>;
 }
 ```
 
 I get this type error

<img width="733" alt="Screen Shot 2021-01-01 at 9 55 02 PM" src="https://user-images.githubusercontent.com/46460840/103451036-0c3e5780-4c7c-11eb-8301-93e2738872b6.png">

The weird thing is, this error goes away if i use the object directly in the `sx` prop instead of the variable.

<img width="476" alt="Screen Shot 2021-01-01 at 9 56 02 PM" src="https://user-images.githubusercontent.com/46460840/103451045-29732600-4c7c-11eb-9a65-628cda2e36a4.png">

**To Reproduce**

See this [CodeSandbox](https://codesandbox.io/s/elegant-swanson-q9drb)

**Expected behavior**

I should not get an error when using a variable.

**Additional context**

Using:
`"theme-ui": "^0.3.5"`
`"@types/theme-ui": "^0.3.7",`

**Comment by hasparus** [comment]
> I should not get an error when using a variable.

Shouldn't you?

What if you write 

```ts
 function Component() {
   const style = { textTransform: "Please transform the text in a nice way, okay?" };
   return <div sx={style}>{children}</div>;
 }
 ```
 
 Notice you'll receive a quite similar error without Theme UI, when you pass your variable to `style` prop.
 
 ```ts
interface FooProps { children: React.ReactNode };

function Foo({ children }: FooProps) {
  const style = { textTransform: "uppercase" };

  return <div style={style}>{children}</div>;
}
```

Here's the error:

 ```
 Type '{ textTransform: string; }' is not assignable to type 'CSSProperties'.
  Types of property 'textTransform' are incompatible.
    Type 'string' is not assignable to type '"-moz-initial" | "inherit" | "initial" | "revert" | "unset" | "capitalize" | "full-size-kana" | "full-width" | "lowercase" | "none" | "uppercase" | undefined'.ts(2322) h
 ```
 
 [**CodeSandbox**](https://codesandbox.io/s/nice-tdd-sj8pf?file=/src/App.tsx)
 
 This error here is a bit better, because we can't nest styles in `style` prop.
 
 So, the problem occurs, because your textTransform is inferred as `string`, and we can't accept _any string_ as textTransform, right? We want it to be `uppercase` or `lowercase` or `initial`...
 
You can read more about it and find two simple solutions here in the docs: https://dev.theme-ui.com/guides/typescript#union-types-are-not-inferred-without-explicit-annotation.

**Comment by hasparus** [comment]
@lachlanjc Another point for urgency of clearer docs and the stable release. [Gatsby docs literally teach React](https://www.gatsbyjs.com/docs/tutorial/part-one/#wait-html-in-our-javascript). I'm not saying we should go that far, but we could link to _recommended read before you use Theme UI_ or sth like that and explain tricky problems you could often encounter like this one?
