### ISSUE TITLE
Gettting pragma and pragmaFrag cannot be set when runtime is automatic when using @jsxImportSource

### ISSUE THREAD

**Issue by dbertella** [system-ui/theme-ui#1474]
**Describe the bug**
I see there is a discrepancy between the official docs and the readme file in github about what pragma to import in order to make the sx prop work. I'm trying to use what I see in the readme that seems more up to date, but it looks like something is missing. Do I have to import a different package in order to have the new pragma available?
I'm using latest Create react app and latest typescript. What's the correct way to handle this nowadays?

Right now I'm getting this error:
```
pragma and pragmaFrag cannot be set when runtime is automatic.
> 1 | /** @jsxImportSource theme-ui */
```

## Dependencies
```
"react": "17.0.1",
    "react-dom": "17.0.1",
    "react-scripts": "^4.0.1",
    "theme-ui": "^0.3.5",
    "typescript": "^4.1.3",
```

Thanks!

**Comment by dcastil** [comment]
Hey @dbertella! The error `pragma and pragmaFrag cannot be set when runtime is automatic` is shown by Babel or the transpiler you're using if the pragma comment for the classic runtime (`/** @jsx jsx */`) is used but the automatic runtime is enabled which doesn't support this comment. I could reproduce it in [the Babel repl](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=PQKhAIAECsGcA9x0SYAoAZgVwHYGMAXASwHsckEAKASnAG8BfIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.12.12&externalPlugins=) (make sure that React Runtime is set to automatic).

I suspect that you're using some kind of Babel plugin which inserts the `/** @jsx jsx */` comment at the top of the file. Are you using react-app-rewired or a Babel macro (or something different that changes the default Babel behaviour of create-react-app)? Or even better: Could you share a reproducible example of your issue?

**Comment by dbertella** [comment]
Hey @dcastil thanks for taking the time to look into this, I'm not using any babel plugin or react-app-rewired, and before updating the dependency I used to add the pragma manually. I'll try to investigate further, but then I don't need to install anything else right? just plain theme ui correct?

```
{
  "compilerOptions": {
    "baseUrl": "src",
    "downlevelIteration": true,
    "lib": [
      "esnext",
      "dom",
      "dom.iterable"
    ],
    "module": "esnext",
    "target": "esnext",
    "sourceMap": true,
    "allowJs": true,
    "esModuleInterop": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "moduleResolution": "node",
    "forceConsistentCasingInFileNames": false,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "noUnusedParameters": true,
    "noUnusedLocals": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "skipLibCheck": true,
    "noEmit": true,
    "preserveSymlinks": true,
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "noFallthroughCasesInSwitch": true
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "webpack",
    "jest",
    "src/setupTests.ts",
    "styleguide.config.js",
    "coverage"
  ],
  "include": [
    "src"
  ]
}
```
this is my ts config just in case. 
I'll try to recreate the environment in a codesandbox and let you know. Do you have a working example perhaps I can look at? With create react app and typescript? Thanks again

> React Runtime is set to automatic

How do I set the runtime? Sorry for the noob question

**Comment by dcastil** [comment]
> I don't need to install anything else right? just plain theme ui correct?

Yes, you should only need to install theme-ui and then use the comment `/** @jsxImportSource theme-ui */` at the top of every file in which you want to use Theme UI.

> Do you have a working example perhaps I can look at? 

I made a minimal working example with create-react-app and TypeScript here → https://codesandbox.io/s/cra-example-theme-ui-3lg5c?file=/src/App.tsx
You can try removing stuff from your app until it looks like the example here to figure out where the problem is exactly.

> How do I set the runtime?

If you're using create-react-app v4.0.0 or higher, you're using the automatic runtime already. The error message you posted only shows up in the automatic runtime. But you can downgrade to the classic runtime by putting `DISABLE_NEW_JSX_TRANSFORM=true` into your env file. More on that here: https://create-react-app.dev/docs/advanced-configuration

**Comment by dbertella** [comment]
oooh ok this is probably what i missed I'm not using alpha version, if you switch to 0.3.5 you'll see the error.
![image](https://user-images.githubusercontent.com/2563196/106662823-cb976e00-659a-11eb-8951-bb772ce37bcd.png)

So which version is safe to use?

**Comment by dcastil** [comment]
Ah yes, that's the issue. Support for the automatic runtime was added in `v0.5.0-alpha.1`. You have two options here:

1. Use the latest stable version `theme-ui@0.3.5` together with the environment variable `DISABLE_NEW_JSX_TRANSFORM=true` in create-react-app and then use the pragma comment and imports for the classic runtime.
2. use an alpha version like `theme-ui@0.5.0-alpha.1` or higher with the automatic runtime like in my example.

If you don't have super tight constraints on stability, I'd go with the alpha (latest is `theme-ui@0.6.0-alpha.6`). Otherwise you'll need to refactor some things once a new stable version is released because so many things changed in the meantime.

**Comment by dbertella** [comment]
Yes I noticed few changes actually but I'm trying latest alpha now. Yeah I totally missed that. Isn't it worth to add a comment in the readme mentioning that? Anyway thank you very much and looking forward for the new version!
