### ISSUE TITLE
Link to 404 page in documentation of /sx-prop

### ISSUE THREAD

**Issue by justin-calleja** [system-ui/theme-ui#1478]
At

https://theme-ui.com/sx-prop

"custom pragma comment" links to a 404 page:

> Under the hood, Theme UI uses a [custom pragma comment](https://theme-ui.com/jsx-pragma) ...

https://theme-ui.com/jsx-pragma doesn't exist anymore.

**Comment by lachlanjc** [comment]
Thanks for the report! Yeah, this has been fixed in the docs on https://dev.theme-ui.com/sx-prop but we haven’t released that to stable yet so it’s not on the main website. We should definitely have a better system for this in the future so docs fixes can be easily rolled out without new package stable releases.

**Comment by justin-calleja** [comment]
Thanks! Sorry for the spam. Didn't know about that.

**Comment by lachlanjc** [comment]
You're great! It's a dumb result of our current system but we only got the alpha release docs up & running recently & haven't taken the time to link between them, etc.

**Comment by hasparus** [comment]
@lachlanjc we can port fixes to `stable` branch for bugs like this, but I totally agree that docs setup needs improvements.
