### ISSUE TITLE
Unsupported Prism Languages

### ISSUE THREAD

**Issue by chibicode** [system-ui/theme-ui#160]
`@theme-ui/prism` uses [`prism-react-renderer`](https://github.com/FormidableLabs/prism-react-renderer), [which does not include all languages supported by Prism](https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js) by default. So if you use one of the missing languages, it simply does not highlight:

```r
# r language
# no syntax highlighting on theme-ui
```

A fix would be to pass `Prism` as a prop on `Highlight` component, [as documented here](https://github.com/FormidableLabs/prism-react-renderer#prism). I think the best approach would be to allow passing `Prism` to [`index.js`](https://github.com/system-ui/theme-ui/blob/master/packages/prism/src/index.js#L7) like this:

```jsx
export default ({ children, className, title, Prism }) => {
  // ...
  
  return (
    <Highlight
	  {...defaultProps}	
      Prism={Prism || defaultProps.Prism}
      ... />
  )
}
```

So that it could be customized like:

```jsx
import CodeBlock from '@theme-ui/prism'
import Prism from 'prismjs/components/prism-core'
import 'prismjs/components/prism-r'

<CodeBlock Prism={Prism} ... />
```

**Comment by johnletey** [comment]
@jxnblk @johno Just following up on this issue, should we maybe add to the documentation noting how since [`prism-react-renderer`](https://github.com/FormidableLabs/prism-react-renderer) doesn't support all languages, we have added the ability to import custom language syntax highlighting? So that future users, when coming across this problem, can look at the documentation?

**Comment by johno** [comment]
It’s worth noting on the readme for sure 👍

**Comment by johnletey** [comment]
Great ... I can open a PR!
