### ISSUE TITLE
Can't override margin of theme-ui components

### ISSUE THREAD

**Issue by acal11** [system-ui/theme-ui#1622]
**Describe the bug**
When applying margin to Box the base style of `margin: 0` overrides whatever is passed down in the sx prop. Is this the intended behaviour? I've just upgraded from v0.3.x where my styles worked as intended.

**Expected behavior**
Base styles should be applied before the sx prop styles.

**Comment by lachlanjc** [comment]
Hmm, that shouldn't be the case! Can you provide a reproduction?

**Comment by fcisio** [comment]
I had the same issue yesterday.
I think it's because of the order the emotion style tags are printed.

Basically, if you use the `sx` prop you're good since it overrides the style of the component.

What doesn't work is when you target lets say `Box` with a class

```js
component: {
  '.item': { // applied to <Box /> : fails
    mt: 2
  },
  'item': { // as a variant : should work
    mt: 2
  },

  '& > * + *': { // currently, something like this doesn't work
    mt: 2,
  }
}
```

My workaround has been to use pragma on a normal HTML tag instead of a Theme UI component.

**Comment by acal11** [comment]
Thanks for the replies - looks like I needed to nuke my node_modules and do a fresh install of everything. I had also upgraded React at the same time, so probably some conflicting packages or something else in there going on.

**Comment by deltaepsilon** [comment]
This has the possibly positive side effect of preventing devs on my team from using margins. I'm oddly in favor of that... but I still want the option to override it.
