### ISSUE TITLE
Add variants to jsx source

### ISSUE THREAD

**Issue by nrakochy** [system-ui/theme-ui#1654]
Thanks for the great library 👍 

**Is your feature request related to a problem? Please describe.**
Expose the `variant` api via custom jsxImport source without having to handle it directly in non-theme-ui components. 

**Describe the solution you'd like**
I think the `variant` api is pretty great. Would you be open to add it into [the jsx parser](https://github.com/system-ui/theme-ui/blob/develop/packages/parse-props/src/index.ts)?

That is, for components that are built outside of theme-ui, in addition to `sx` and `css`,  it would be helpful if the import source would also handle `variant`. If I had access to the handler from `Box`

```js
const variant = ({ theme, variant, __themeKey = 'variants' }) =>
  css(get(theme, __themeKey + '.' + variant, get(theme, variant)))
```
it would allow me to include it for free through my codebase

```js
export interface MyCustomProps extends ExistingProps {
    sx?: SxProp;
    variant?: string;
}
```

**Describe alternatives you've considered**
No alternatives, just an api that makes non-theme-ui components more `theme-ui`-like

**Additional context**
In my case, I am introducing `theme-ui` into an existing React codebase, and this would facilitate adoption with a shared api by only adding the requisite comment at the top of the file.

**Comment by hasparus** [comment]
Hey nrakochy. Thanks for the issue!

I'd like to know what @lachlanjc thinks, but I'd rather not add anything like this to the public API.

1. There is an alternative: You can use

```tsx
sx={{ variant: 'my-variant' }}
```

2. `variant`, unlike `sx` is a pretty common word to appear in React props. I would rather not put my hands on it and proclaim that all `variant` props will now belong to Theme UI. We don't have to look far for a problem — a global `variant` would conflict with components in `@theme-ui/components` (The behaviour of `<Button variant={} />` would be different depending on JSX pragma being set or not.)

**Comment by lachlanjc** [comment]
Yep, agreed. This breaking change could be pretty disastrous for some users, & cause issues they wouldn't be able to elegantly fix: like with third-party components that accept a `variant` prop, if the JSX pragma is set up project-wide, I don't know how that would work.

The docs could use a pretty significant restructuring I haven't spent the time writing yet, but basically I want a new page explaining the various ways Theme UI can be used: though Components, or through the pragma on each file, or a project-wide pragma, plus through MDX & Themed. Then, rewriting the top of the SX prop page to explain that's either on components or via the pragma, linking to the Variants docs. Then grouping several remaining pages into an API Reference section so we can better steer new folks towards the important features. I think in the end this issue is a sign that our current docs don't explain this clearly enough, which is absolutely the case. But due to the extremely breaking change adding this prop would be, I don't think it makes sense.

**Comment by nrakochy** [comment]
Yes that make sense. A breaking change is simply out of the question. 

Taking a step back, perhaps it is helpful to rethink in terms of my overall feature req. My goal would be to introduce `theme-ui` into an existing component library codebase. 

```js
Goal: distribue theme-ui api through existing lib
```

Ideally, consumers of said component would be then able to go to the `theme-ui` docs and leverage all of the power that it offers, access to theme, sx, variants, etc. irrespective of whether it is a proper `theme-ui` component or one that was wrapped from elsewhere. 

So, perhaps you might consider a custom, opt-in `jsxImport` source? That is, as one who helps maintain this custom wrapper lib, I would intentionally opt into the api and be responsible for whatever consequences might be.

**Comment by hasparus** [comment]
> So, perhaps you might consider a custom, opt-in jsxImport source? That is, as one who helps maintain this custom wrapper lib, I would intentionally opt into the api and be responsible for whatever consequences might be.

I'll star your repo on GitHub if you do it, and I can help you out if you need some help with building on top of Theme UI, but there's no way I'm merging it here. I'm sorry — Theme UI is already too big IMHO.

**Comment by lachlanjc** [comment]
Yep, we're happy to link to other libraries on the https://theme-ui.com/resources page!
