### ISSUE TITLE
:checked not working on switches

### ISSUE THREAD

**Issue by luuk777w** [system-ui/theme-ui#1671]
**Describe the bug**
I would like to have different variants of checkboxes or switches. The default checked state is the primary color. This does not change if you change it in your theme or add it in the `sx` prop.

**To Reproduce**
add a switch and add this to your theme:

```ts
   forms: {
        switch: {
            "&:checked": {
                bg: "red"
            }
        }
    }
```

You can also add this to the `sx` prop:

```ts
"&:checked": {
        bg: "red"
    }
```

**Expected behavior**
The switch is red when it is checked.

**Actual behavior**
The switch is still the primary color.

**Comment by flo-sch** [comment]
Hi @luuk777w, I faced similar issues trying to style that one.

This is because the Switch component renders several elements, and the [HTML `input` itself is hidden](https://github.com/system-ui/theme-ui/blob/24bf23a618fc57ba3ee999a4280b8bd63465380e/packages/components/src/Switch.js#L21), thus such native rule CSS selector not having any visible effect.

A potential workaround ([as used by the component itself](https://github.com/system-ui/theme-ui/blob/24bf23a618fc57ba3ee999a4280b8bd63465380e/packages/components/src/Switch.js#L61)) is to use `input:checked ~ &` instead

I created a code-sandbox to verify it: [CodeSandbox demo](https://codesandbox.io/s/switch-state-style-2j2qs?file=/src/AppTheme.ts)

Would that solve your issue?

**Comment by luuk777w** [comment]
Hi @flo-sch,

Thank you for responding to my issue this Sunday evening.
This definitely solves my problem.

**Comment by lachlanjc** [comment]
Appreciate your assistance @flo-sch! If you think this is worth adding to the component page's docs, let's do it

**Comment by flo-sch** [comment]
Sounds good, I will create a PR ;)
