### ISSUE TITLE
[typography][gatsby] Do I always have to use `Styled` for typography when it comes to themes?

### ISSUE THREAD

**Issue by daydream05** [system-ui/theme-ui#172]
Before migrating to theme-ui w/ typography, I would usually have to add `gatsby-plugin-typography` to my gatsby-config

```js
{
    resolve: `gatsby-plugin-typography`,
    options: {
        pathToConfigModule: `src/utils/typography`,
    },
}
```

and the typography would work globally. 

When building gatsby themes, can I use the old way where typography would work globally, or would I now need to follow the theme-ui convention, which is doing `Styled.h1`?

**Comment by johno** [comment]
Using `theme-ui` is not a required library for working with Gatsby themes.

It will be used in official Gatsby themes to ensure that they're interoperable with other themes by avoiding global styles. This is a requirement for official themes, and a recommended approach, because typography.js introduces global styles which will clash when composing themes together.

As such, we began building Theme UI to provide many of the same primitives and awesome config of Typography.js ([in fact typography.js config is compatible with theme-ui](https://theme-ui.com/typography)), while being able to be certain their won't be any global style clashing.

That said, depending on the needs of your use case, and how your theme will be used, it might make sense to continue using `gatsby-plugin-typography`. As always, it depends 😸 

> Can I use the old way where typography would work globally, or would I now need to follow the theme-ui convention, which is doing Styled.h1?

Theme UI will require you to use the `Styled.h1` directly when outside of MDX.

---

Hopefully that helps, let us know if you have any other questions!

**Comment by daydream05** [comment]
Got it, thanks! That makes a lot of sense. The lazy me was so used to having my headings/paragraphs automatically styled for me after using typography.js. I'll start using `Styled.h1` since official themes will do it that way 😊.

The typography primitives plus the base theme presets that you all made are so very nifty! I realized that when making a theme, the parent site would override the theme anyway so the base theme's theme _doesn't_ really matter. So it's really cool that I can just grab them from theme-ui and go from there. You and the team really thought of everything! 😭

**Comment by kuworking** [comment]
@daydream05 You probably know but (just in case) you can use your styled components as usual (I just noticed this few days ago, superhappy about it 💃 )

```js
const Title = styled(Styled.h1)`
  background: #ccc;
`
```
