### ISSUE TITLE
borderCollapse ::: Type 'string' is not assignable to type 'StylePropertyValue<BorderCollapse>'

### ISSUE THREAD

**Issue by jeffscottward** [system-ui/theme-ui#1861]
**Describe the bug**
Attempt to use `borderCollapse` with either correct value ( `'collapse`,`'separate'` ) and typescript will throw errors.

**To Reproduce**
In the `styles` object, use `borderCollapse` on `table` or `th` or `td` and you will get an error.

**Comment by hasparus** [comment]
Okay, I don't have any code snippet, but it seems that the problem you're getting occurs because you try to assign a string with value "collapse" and type string to a property that accepts values of type ` "collapse" | "separate" |  "-moz-initial" | "inherit" | "initial" | "revert" | "unset"`.

We could add `string & {}` to _BorderCollapse_ type, but it's in `csstype`'s repo.

![image](https://user-images.githubusercontent.com/15332326/125440796-32d585e4-b187-4c2c-870e-f3b5b5f05db0.png)

So here's my guess of what happens:

```ts
const styles /* no annotation here */ = { th: { borderCollapse: "collapse" } };

const theme: Theme = {}
```

TypeScript doesn't know that `styles` is supposed to be `ThemeStyles`, so it infers that `th.borderCollapse` is a string.

What you can do instead is either defining styles inside of `theme` or annotating it with `: ThemeStyles`.

You can read more about it in the docs: https://theme-ui.com/guides/typescript/#union-types-are-not-inferred-without-explicit-annotation

**Comment by jeffscottward** [comment]
Glad you already had a solution for it.
Wondering why this doesn’t happen for something like display block, flex,
etc if the values are string based. Why is this an outlier?

**Comment by hasparus** [comment]
Well, it depends on the definition from `csstype`. I'd guess that the reasoning here is that no "custom value" for borderCollapse is legal, and stuff like `borderEndRadius` can be `4px` or even `calc(4px * var(--something))`.

**Comment by jeffscottward** [comment]
Display doesn’t have custom values either though?
Basically should I file a bug for this with css type?

**Comment by hasparus** [comment]
> Display doesn’t have custom values either though? Basically should I file a bug for this with css type?

I wouldn't. `csstype` is generated from `mdn/data` so it's a bit more complex too.

In general this is intended TS error to fix in your codebase.
