### ISSUE TITLE
docs: Specify MDX version to install

### ISSUE THREAD

**Issue by aryanjha256** [system-ui/theme-ui#2133]
### **Server Error**

`Error: require() of ES Module C:\Users\ARYAN\Desktop\itsaryan\node_modules\@mdx-js\react\index.js from C:\Users\ARYAN\Desktop\itsaryan\node_modules\@theme-ui\mdx\dist\theme-ui-mdx.cjs.dev.js not supported.
Instead change the require of index.js in C:\Users\ARYAN\Desktop\itsaryan\node_modules\@theme-ui\mdx\dist\theme-ui-mdx.cjs.dev.js to a dynamic import() which is available in all CommonJS modules.`

This error happened while generating the page. Any console logs will be displayed in the terminal window.

![Screenshot 2022-02-13 191552](https://user-images.githubusercontent.com/76901229/153756054-a5aedd47-66d8-40d2-ad44-7f56da8f61a5.png)

**Comment by lachlanjc** [comment]
Yep, unfortunately this is a known issue, we just haven't figured out the resolution: https://github.com/system-ui/theme-ui/issues/2023

We don't yet support MDX v2, which was recently released. The fix is to downgrade `@mdx-js/react` to the latest version of v1, & you should be good to go.

**Comment by jacksonbrim** [comment]
> 

Can you please update the documentation in the ReadMe and on the website so that the info reflects installing mdx-js/react v1? This project is used in a popular, but older tutorial that's causing some headaches for newbies.


`npm install theme-ui @emotion/react @mdx-js/react@1`

For yarn:
`yarn add theme-ui @emotion/react @mdx-js/react@1`

**Comment by john20xdoe** [comment]
**Notes** (since the original title indicates next.js was being used):

Downgrading to the v1 of mdx-js (1.6.22?) makes it depend only up to react@17.
So those who already use react@18 and above (for example, users of latest NextJS), will not be able to use the downgrade workaround unless they also downgrade the other.
![image](https://user-images.githubusercontent.com/14521605/172303885-f7e43011-2d32-4845-9250-e65d6d2865b6.png)

**Comment by hasparus** [comment]
@john20xdoe Please use `--legacy-peer-deps` for now. MDX 1 doesn't depend on React 17, it was just written at the time React 17 was the newest version.

**Comment by john20xdoe** [comment]
@hasparus ooh, didn't realize there's an option for that. Thanks

**Comment by moimikey** [comment]
these feels like a bandaid fix. i use `projen` and by default when it tries to install my node dependencies, it errors on necessitating `--legacy-peer-deps` which is bothersome. is there a long-term workaround coming soon?

my current solution is throwing this into `.npmrc`, so the flag isn't explicitly needed for CI and newly onboarded devs who would otherwise run into this error:
```
legacy-peer-deps=1
```

**Comment by hasparus** [comment]
:rocket: Issue was released in [`v0.15.0-develop.23`](https://github.com/system-ui/theme-ui/releases/tag/v0.15.0-develop.23) :rocket:
