### ISSUE TITLE
Define single padding/margins property using "spaces"

### ISSUE THREAD

**Issue by imjordanm** [system-ui/theme-ui#251]
Sorry if there is a way of currently doing this, but I'm trying to avoid having separate css properties for padding-top, padding-right, and so on when making use of the "spaces" values.

An example in the theme-ui index file utilizing the value for index 2 in the "spaces" array:
`padding: 2`

This works fine, but when I go about using different values for each side:
`padding: 2 3 2 3`

I can't use this, so I currently get around it by doing:
`pt: 3,
 pr: 2,
 pb: 3,
 pl: 2`

Is there a way of achieving this? Thank you!

**Comment by jxnblk** [comment]
The shorthand CSS property will only work if you return a string value with units, so `padding: '8px 16px 8px 16px'` will work but `2 3 2 3` will probably throw an error in JS due to the spaces.
Looking at your example, you could use the Theme UI x- and y-axis shorthands, `{ paddingX: 3, paddingY: 2 }` (or `{ px: 3, py: 2 }`), but you can also pass a function as a value if you really want to use the CSS shorthand: ```padding: t => `${t.space[2]}px ${t.space[3]}px` ```

**Comment by imjordanm** [comment]
The px and py solution is perfect! I should've known to try that one. Maybe I didn't look hard enough, but are there docs somewhere for these theme-ui specific shorthand properties?

Thanks again!

**Comment by jxnblk** [comment]
No problem! The docs could certainly be better, but here's a reference for values that can be used in the `sx` prop: https://styled-system.com/css/
