### ISSUE TITLE
useRootStyles: false disables whole theme

### ISSUE THREAD

**Issue by pietrofxq** [system-ui/theme-ui#2516]
**Describe the bug**
When using  `useRootStyles: false`, the default theme is not returned and variables in components do not work. The issue is here:
https://github.com/system-ui/theme-ui/blob/20a2e7e9c65eeb3d52019625c412b2c16eeb93ff/packages/color-modes/src/custom-properties.ts#L78

I am not sure if we need to check `useRootStyles` at all here, the documentation says this property is only to avoid applying styles in the html, not that it would prevent the color mode from working

**To Reproduce**

1. set useRootStyles: false in theme
2. try to access a variable in a component, or check the devtools: 
![image](https://github.com/user-attachments/assets/216c320a-cd82-491a-8650-a977900fd651)

**Expected behavior**
`useRootStyles: false` should not prevent variables from being defined

**Comment by hasparus** [comment]
What framework are you using?

**Comment by pietrofxq** [comment]
Developing a chrome extension with react, I used patch-package to make it work correctly by changing this:

```
-  if (!colors || useRootStyles === false) return {};
+  if (!colors) return {};
```

```
   return css({
     ...styles,
-    color: colorToVarValue('text'),
-    bg: colorToVarValue('background')
+   ...(useRootStyles ? {color: colorToVarValue("text"), bg: colorToVarValue('background')} : {})
   })(theme);
```

**Comment by hasparus** [comment]
> the documentation says this property is only to avoid applying styles in the html, not that it would prevent the color mode from working

Okay, I get it. So this function is used only to affect the global style for `html` element, which is why it was disabled like that, but you don't have a nested ColorModeProvider so there's nothing providing color variables for you.

It starts working again if you add a nested `ThemeUIProvider` or turn `config.useCustomProperties` to `false`, but it is in fact a bug.

Thanks! Good catch.

[CodeSandbox](https://codesandbox.io/p/sandbox/z8pxlw?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm2c7iwiv00063b6mzp6vmrb9%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm2c7iwiv00023b6m07rwbb1q%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm2c7iwiv00033b6mkgp15445%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm2c7iwiv00053b6mostxh5bn%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm2c7iwiv00023b6m07rwbb1q%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm2c7iwiv00013b6m8whc13rw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522cm2c7iwiv00023b6m07rwbb1q%2522%252C%2522activeTabId%2522%253A%2522cm2c7iwiv00013b6m8whc13rw%2522%257D%252C%2522cm2c7iwiv00053b6mostxh5bn%2522%253A%257B%2522id%2522%253A%2522cm2c7iwiv00053b6mostxh5bn%2522%252C%2522activeTabId%2522%253A%2522cm2c7iyt9000p3b6mkzqfi1dq%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm2c7iwiv00043b6mcsffa0be%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cm2c7iyt9000p3b6mkzqfi1dq%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm2c7iwiv00033b6mkgp15445%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm2c7iwiv00033b6mkgp15445%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by hasparus** [comment]
@pietrofxq https://github.com/system-ui/theme-ui/pull/2519 should solve this.

**Comment by pietrofxq** [comment]
awesome thank you!
