### ISSUE TITLE
[0.17.0] csstype version locked to 3.0.10

### ISSUE THREAD

**Issue by jlowcs** [system-ui/theme-ui#2520]
**Describe the bug**

The latest release of `@theme-ui/css` changed the version of `csstype` from `^3.0.10` to `3.0.10`, which results in a downgrade for me as I was actually using the `3.1.3` version. Now I'm having some type checking issues on `aspectRatio` because `3.0.10` doesn't allow for numbers, whereas `3.1.3` does.

**To Reproduce**

```tsx
<div sx={{ aspectRatio: 0.5 }} ></div>
```

=> `Type 'number' is not assignable to type 'StylePropertyValue<AspectRatio | undefined, Theme<{}>>'` on `0.17.0`

**Comment by hasparus** [comment]
Ouch, it seems `csstype@3.0.10` expects a string there :/

I locked the version because bumping to 3.1.3 failed some of our tests, and some it has some changes that made previously wrong code typecheck correctly. Sorry for that 😓 

I've changed it back to use a caret `^` prefix for version resolution. This should solve your problem.

Fixed by https://github.com/system-ui/theme-ui/commit/401b7945a61aa5001e8abaaf1c56751c503d5d89
