### ISSUE TITLE
[question] preference for styling Gatsby theme components?

### ISSUE THREAD

**Issue by ekafyi** [system-ui/theme-ui#256]
_(Apologies for the "issue spam", not sure where to ask this!)_

I know this might be a matter of preference, but what would be considered best practice for using Theme UI in UI components? Specifically for Gatsby theme components that might be shadowed by other users.

## Option A

Only use variants in the theme object for common/general elements (buttons, headings, text styles). Any "custom" styling is done in the UI component.

```js
// src/components/tomato-box.js
/** @jsx jsx */
import { jsx } from "theme-ui"

const TomatoBox = props => (
  <div sx={{ 
      background: "tomato",
      color: "#000",
      p: 3,
      textAlign: "center",
      "&:after": {
        content: '"🍅🍅🍅🍅"',
      } }}>
    {props.children}
  </div>
)
export default TomatoBox
```

Example from the official blog theme: https://github.com/gatsbyjs/gatsby/blob/master/themes/gatsby-theme-blog/src/components/bio.js#L30-L33

## Option B 

Make heavy use of variants in the theme object for UI components; if an element needs more than (eg.) 2 CSS declarations, put the styles away in a variant.

```js
// src/components/tomato-box.js
/** @jsx jsx */
import { jsx } from "theme-ui"

const TomatoBox = props => (
  <div sx={{ variant: "components.tomatoBox" }}>
    {props.children}
  </div>
)
export default TomatoBox
```

```js
// src/gatsby-plugin-theme-ui/index.js

export default {
  // ...
  components: {
    tomatoBox: {
      background: "tomato",
      color: "#000",
      p: 3,
      textAlign: "center",
      "&:after": {
        content: '"🍅🍅🍅🍅"',
      }
    }
  }
}
```

With Option A, you only work on one file instead of two and you can see the entire code at once. But Option B makes the component cleaner and more compact, not cluttered with styling, especially for larger components with complex styling.

Is there any strong reason to adopt Option A over B?

**Comment by jxnblk** [comment]
No worries! Questions like this are super helpful! 

Personally, I think *either* approach can make sense, and it depends on how you want to define the end user API. If you're trying to build a *highly* themeable theme, that can be customized in a single object, Option B could make sense. If you don't expect the theme to require a lot of style customization, Option A is nice because you'll have styles collocated with the components, and if a user shadows the one component, they have more control over how to change the styles in that single component.

Broadly speaking, I tend towards keeping styles collocated with the component, then abstract them into separate components when I notice duplication or certain trends. With Gatsby themes, the more modular your components are, the more flexible the shadowing API will be, so something else to keep in mind as well

**Comment by ekafyi** [comment]
Thank you for your detailed answer! Closing this as well (this _really_ was the last question, LOL).
