### ISSUE TITLE
Change `theme-ui` peer dependencies

### ISSUE THREAD

**Issue by ifiokjr** [system-ui/theme-ui#273]
Currently `theme-ui` has the following dependencies

https://github.com/system-ui/theme-ui/blob/5dbb4dd67d924eb255e45cf5ce48a6efe548e949/packages/theme-ui/package.json#L14-L27

I propose moving the `@mdx-js/react` from a peer to a direct dependency and moving the `react` dependency to peers.

Every project that uses `theme-ui` will have `react` installed so it can afford to be a peer. As for `mdx` I'm really not using it anywhere else in my code.

I might be missing something though, so feel free to close if this has already been discussed.

**Comment by jxnblk** [comment]
It's typical for all of these to be hard-dependencies in a package like this. While `react` will work fine as a hard-dependency, the only reason the others are peer dependencies is because the use of React context in those libraries means that when duplicates are installed, the context does not work at all. Ideally a package like Theme UI could be installed without needing the additional peer dependency installs, but the current setup is to help minimize the likelihood of errors due to duplicate dependencies

**Comment by ifiokjr** [comment]
> the only reason the others are peer dependencies is because the use of React context in those libraries means that when duplicates are installed, the context does not work at all

@jxnblk I wasn't aware of this. Thanks for the explanation.
