### ISSUE TITLE
Theme UI vs Styled System

### ISSUE THREAD

**Issue by woro83c** [system-ui/theme-ui#64]
In simple terms, I'm just wondering why you'd choose this over styled system? My understanding so far is its a layer on top of style system to help streamline a few things such as general layout creation, as well as offering the ability to style certain components from the context of a theme file?

Cheers!

**Comment by jxnblk** [comment]
Generally I don't see it as an either or, since both libraries should be compatible with one another; Theme UI packages up a few other things, so if you want a higher-level abstraction and don't want to set up everything from scratch, it can help speed things up. I tried to add a little bit of the thinking to the docs here as well: https://theme-ui.com/guides/motivation#how-is-this-different-from-styled-system

**Comment by woro83c** [comment]
Awesome, cheers 👍

**Comment by DanielTamkin** [comment]
https://theme-ui.com/motivation#how-is-this-different-from-styled-system is now a 404.
![image](https://user-images.githubusercontent.com/9532762/122946167-c2871d80-d33e-11eb-86a9-092f7e33bedd.png)
Womp Womp :(

**Comment by hasparus** [comment]
Thanks @DanielTamkin! I'm gonna look for this page in our git history and set up some automation to ensure we don't lose stuff so easily.

Oh, it looks like it was moved to `/guides/motivation`. I edited the link in Jackson's post, but we're gonna redirect from `/motivation` anyway.
