### ISSUE TITLE
useColorMode returns incorrect colorMode when components are mounted

### ISSUE THREAD

**Issue by AlexanderMoroz** [system-ui/theme-ui#645]
**Describe the bug**
I'm using gatsby with gatsby-plugin-theme-ui (0.3.0), theme ui v - 0.3.1.
When component is mounted and dark mode was previously chosen and saved to local storage - first value is 'default' and only on next prop render I have 'dark' value. 

Gatsby plugin is included in 'gatsby-config.js'. For check I've added my own console.log to 'InitializeColorMode' from @theme-ui/color-modes and seems it works correctly, but anyway in React I have 'default' first. 

Problem that I need to trigger some animations on colorChanges, so I have useless animations on page load

Is it possible to avoid this? 

**Steps to reproduce** 
clone https://github.com/AlexanderMoroz/theme-ui-gatsby-flicker-test
reload page
check console

**Comment by jxnblk** [comment]
I don't know of a really great way to handle this specific case since React is rendered statically (which can't retrieve values from `localStorage`), and then hydrated on the client with a new color mode. You might be able to replicate some of the functionality in the Gatsby plugin to set styles with CSS, but I don't know how you could do that in React

**Comment by AlexanderMoroz** [comment]
Yeah, pretty logical that during SSR we don't have any info about client's localstorage. Thanks anyway, will try to find any workaround for this.
