### ISSUE TITLE
`deep` secondary color

### ISSUE THREAD

**Issue by rumpl** [system-ui/theme-ui#650]
**Describe the bug**
I must be doing something wrong, I am using the `deep` preset theme and the secondary colour seems the same as the primary.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://codesandbox.io/s/friendly-neumann-z4vj1
4. See secondary `Button` with same color as the `primary` one.

**Expected behaviour**
The second button should have the secondary colour.

Thanks for all your hard work, I'm just checking out theme-ui with rebass and they seem awesome.

**Comment by mrmartineau** [comment]
Hi @rumpl, looking at the [source code](https://github.com/system-ui/theme-ui/blob/master/packages/preset-deep/src/index.js#L11-L12) for the deep theme the two colours are indeed different. You're problem is not with the colours per se, but the fact that the `deep` theme does not provide any variants for buttons, which is what you are trying to use.

In order to have a `secondary` variant for the `Button` component, you will need to define it in your theme. Take a look at [the docs](https://theme-ui.com/components/button) on the `Button` component.

Here is a fork of your CodeSandbox with a basic implementation of what you need to do: https://codesandbox.io/s/nostalgic-goodall-bjypl

Hope that helps

**Comment by rumpl** [comment]
Makes sense, thanks a bunch!
