### ISSUE TITLE
Linting with stylelint

### ISSUE THREAD

**Issue by CommerceOwl** [system-ui/theme-ui#666]
**Is your feature request related to a problem? Please describe.**

It would be nice to have a styelint support. https://stylelint.io/ . Basically, I want to know that the CSS values and such I throw in the theme and inline aren't garbage but valid CSS.

**Describe the solution you'd like**

https://stylelint.io/ seems like a good solution. Styled components implements it.

**Comment by jxnblk** [comment]
I've not used this before, but if this works with Emotion, it should work with this library

**Comment by bearror** [comment]
Eventual support would be really useful - but there likely isn't all that much that can be done to help in Theme-UI itself. For context, at least the following things make `stylelint` usage in a `Theme` a little tricky.

While `stylelint` supports CSS-in-JS, it needs some way of recognizing which objects are styles. Using the `css` import from either `@emotion/core`, or `theme-ui` work fine for providing linting, but both output `SerializedStyles` instead of `SystemStyleObject`. So one can't do:
```tsx
export const alerts: {[key: string]: SystemStyleObject} = { // TypeError
  primary: css({ // Provides linting to the `alerts.primary` variant
    color: "background",
    backgroundColor: "primary"
  })
};
```

One workaround would be to use a POJO:
```tsx
const primary = {
  color: "background",
  backgroundColor: "primary"
};
css(primary); // Provides linting to the `primary` object

export const alerts: {[key: string]: SystemStyleObject} = {
  primary // Exports as a variant, e.g. `theme.alerts.primary`
};
```

It's not that simple, though, as the next hurdle would be resolving the actual differences between `SerializedStyles` and `SystemStyleObject`. Examples would be [responsive values](https://theme-ui.com/sx-prop#responsive-values), [functional values](https://theme-ui.com/sx-prop#functional-values), and Theme-UI -specific properties (such as `bg` or `paddingX`).

---

I'm not familiar with writing PostCSS syntaxes, but I'd say that the way forward here would be to:

1. Look into adding support in https://github.com/stylelint/postcss-css-in-js. In practice, perhaps this could be done via something like a `/* stylelint-parse-object */` comment to flag individual objects for linting. (Although that's admittedly the least elegant solution, and doesn't address responsive or functional values by itself.) 

2. Authoring a [plugin](https://stylelint.io/developer-guide/plugins) that adds and overrides Theme-UI -specific rules to `stylelint`.

**Comment by lachlanjc** [comment]
We’d love to have this in the future, but aren’t planning to build it ourselves. If you’d like to contribute it, go for it!
