### ISSUE TITLE
Unable to style anchor tags from /src/gatsby-plugin-theme-ui/index.js

### ISSUE THREAD

**Issue by cdvillard** [system-ui/theme-ui#755]
**Describe the bug**
Within a Gatsby project using the `gatsby-plugin-theme-ui` plugin, I'm able to set up styles using `sx` for any anchor tag generated using Gatsby's 'Link' component, but changes don't seem to affect those anchor tags when styled in `/src/gatsby-plugin-theme-ui/index.js`. I've found no explicit statements saying they shouldn't, and other elements such as headers seem to receive global styling.

**To Reproduce**
1. Stand up a Gatsby project using `gatsby-plugin-theme-ui`.
2. Under `/src/gatsby-plugin-theme-ui/index.js`, declare styles for `a` tags under `styles` in the default export.
3. Run `gatsby develop` and load any page with an anchor tag generated by the `Link` component.

**Expected behavior**
Anchor tags generated by the link component should inherit styles from those declared globally in `/src/gatsby-plugin-theme-ui/index.js`. 

**Screenshots**
![screenshot showing the code to style links, showing the code reflected in the React Component inspector, and showing that links are not receiving the styles](https://user-images.githubusercontent.com/6250214/76558678-1fc1cd00-6474-11ea-92f7-b5d286403b9b.png)

**Additional context**
So I know Gatsby has some special sauce behind how it uses React, but given that anchor tags are still receiving styles using `sx`, I don't see how these aren't applied after everything is rehydrated. I'm also a relative React noob, hence a lack of any real debugging on my part.

**Comment by lachlanjc** [comment]
This actually is not a bug, it’s the expected behavior, see the highlighted note here: https://theme-ui.com/styling-mdx

If you’d like to use your `a` style outside MDX, you have a few options:

- Use the `Styled.a` component as [documented here](https://theme-ui.com/api#styled)
- Wrap your text content in `BaseStyles`, as [documented here](https://theme-ui.com/api#basestyles)
- Use a text [variant](https://theme-ui.com/guides/variants) directly on those links to add styling

**Comment by cdvillard** [comment]
Okay, cool! You're more than welcome to close this for now. I'll read through these and re-submit something if none of these work for me.
