### ISSUE TITLE
[HELP] Functional value for shadow

### ISSUE THREAD

**Issue by danhab99** [system-ui/theme-ui#786]
Ok so I want to add a primary dropshadow. Right now I have this:

theme.js
```javascript

export default {
  ...
  color: {
    primary: '#213453'
  },
  ...
  shadows: {
    default: '11px 11px rgba(0,0,0,0)',
    primary: theme => `10px 10px ${theme.colors.primary}`
  },
  ...
  cards: {
    primary: {
      ...
      boxShadow: 'default',
      '&:hover': {
        boxShadow: 'primary'
      }
    }
  }
}
```

But when I try to do this, `<Card />`'s don't have the primary shadow on hover. Did I missunderstand then [Functional Value](https://theme-ui.com/sx-prop#functional-values) docs or is this the wrong way of doing it?

**Comment by jxnblk** [comment]
Functional values only work in the `sx` prop or in a *variant* definition. If you want to reuse a color value in the `theme.shadows` scale, you can define colors before the `theme` object

**Comment by danhab99** [comment]
I figured as much.

**Comment by smerth** [comment]
@jxnblk and @danhab99, 

Can you explain this line: "If you want to reuse a color value in the theme.shadows scale, you can define colors before the theme object"

That "theme object", are you referring to a variant, or the shadows scale object.

Here is a theme shadows scale with two values:

    export const shadows = {
      1: "2px 2px #888888",
      2: theme => `2px 2px ${theme.colors.secondary}`,
    };

As stated "2" does not work because "Functional values only work in the sx prop or in a variant definition."

When you say "If you want to reuse a color value in the theme.shadows scale, you can define colors before the theme object" it seems to imply there is a way to use a theme.colors.SOME-VALUE in a key of the shadows object... 

But I can't figure out how to do that.

**I know I can create a variant to apply a shadow.** If possible I want to define my shadows in the shadows scale object using theme colors.

I that possible?

Thanks!

**Comment by jxnblk** [comment]
Sorry if that was unclear. I meant define `colors` before the `theme` object:

```js
const colors = {
  primary: 'blue',
}

const theme = {
  colors,
  shadows: {
    small: `0 2px 1px 1px ${colors.primary}`,
  }
}
```
