### ISSUE TITLE
Support disabling of HTML autocomplete on Input component

### ISSUE THREAD

**Issue by suaurial** [system-ui/theme-ui#921]
It'd be great if we could specify autocomplete="off" to disable HTML autocomplete on the Input component. Nothing happens when I currently try to add that, but please correct me if this already exists and I'm just doing something wrong.

**Comment by lachlanjc** [comment]
Hey! The `Input` component [forwards all props](https://github.com/system-ui/theme-ui/blob/master/packages/components/src/Input.js#L9) you pass it—nothing special happens to `autocomplete`. It’s more likely you need to replace it with [`autoComplete`](https://stackoverflow.com/questions/37503656/react-doesnt-render-autocomplete-off), which React/JSX uses instead of the lowercase variant in HTML: https://reactjs.org/docs/dom-elements.html

**Comment by lachlanjc** [comment]
I think we can close this issue

**Comment by lachlanjc** [comment]
@hasparus Can you close this?
