### ISSUE TITLE
useBreakpointIndex defaultIndex breaks hydration

### ISSUE THREAD

**Issue by wereHamster** [system-ui/theme-ui#924]
**Describe the bug**

You should never ever initialize React state differently on server and client (ie. any use of `typeof window === "undefined"` or `process.browser` must be avoided). Not respecting this will cause the UI to be misrendered (not correctly updated after hydration). If you are lucky then React will print a warning (eg. Warning: Prop `className` did not match. Server: "css-14r1nkj" Client: "css-37oxbl"). If you are less lucky, you won't see any warning and wonder why the UI is wrong.

**To Reproduce**

https://codesandbox.io/s/kind-satoshi-65goi

The data-index attribute on the div is not updated, it remains 0 after client loads on a larger screen (but the inner text of the div is updated correctly).

**Relevant Code**

https://github.com/system-ui/theme-ui/blob/6663b23facd5e3cd797f9cede10c08599a73b83f/packages/match-media/src/index.ts#L15-L34

The `getIndex()` function is used to initialize the default value... but the value is not updated after client hydration (ie. inside useEffect).

**Comment by juanpprieto** [comment]
+1 here. 

Not sure if this entirely my same root cause, but a similar issue has been driving me crazy in Gatsby's SSR too. Both useResponsiveValue and Index don't seem to always re-hydrate/refresh once a component is mounted. In most cases, SSR seems to render the correct mq'd styles and the default or passed defIndex class, but often unless I manually force (CSR only) with a conditional state or force a re-render by a useEffect/useState it will get stuck on the default bp until a viewport resize.

This is particularly annoying when trying to create responsive layout components with optional directional layouts like a Flexed list that can be either horizontal or vertical.

thanks in advance for any pointers!

**Comment by wereHamster** [comment]
@juanpprieto it's very likely caused by the same issue.

**Comment by giautm** [comment]
I facing with same issue, when use `useBreakpointIndex` with NextJS.

My solution was almost same as @wereHamster. 

`defaultIndex` was not helpful in this case, and should be removed. Initial value of `useBreakpointIndex`, should set to `null` on both client & server sides. Then, `useEffect` will run on client side then update index to correct value. Assume about mobile/desktop on server side was not correct approach to resolve problem.

```ts
import { useState, useEffect, useCallback, useLayoutEffect } from 'react'
import { useThemeUI } from '@theme-ui/core'

const defaultBreakpoints = [40, 52, 64].map(n => n + 'em')

export const useBreakpointIndex = () => {
  const context = useThemeUI()
  const breakpoints =
    (context.theme && context.theme.breakpoints) || defaultBreakpoints

  const getIndex = useCallback(() => {
    return breakpoints.filter(
      breakpoint =>
        window.matchMedia(`screen and (min-width: ${breakpoint})`).matches
    ).length
  }, [breakpoints])

  const [value, setValue] = useState(null)
  
  useEffect(() => {
    const onResize = () => {
      setValue(getIndex())
    }
    onResize();
    window.addEventListener('resize', onResize)
    return () => window.removeEventListener('resize', onResize)
  }, [breakpoints, getIndex])

  return value
}
```
