### ISSUE TITLE
Textarea doesn't support resize style or prop

### ISSUE THREAD

**Issue by madebyankur** [system-ui/theme-ui#963]
**Description**
The Textarea component does not include any style or prop for the resize property, which is fairly standard on an HTML Textarea. This leads to some odd behavior where the Textarea can be resized beyond its container.

**To Reproduce**
1. Go to: https://theme-ui.com/components/textarea/
2. Resize the Textarea component outside the container.
3. Update Textarea to include resize property or style.
4. 

**Expected behavior**
The resize property should be available on the Textarea component for use in different scenarios (i.e. none, vertical, horizontal)

**Screenshots**
![image](https://user-images.githubusercontent.com/12908185/83173259-0cd8a380-a119-11ea-89d6-e5fc8ecc2ed5.png)

**Additional context**
-

**Comment by lachlanjc** [comment]
<img width="758" alt="Screen Shot 2020-05-29 at 10 11 02 AM" src="https://user-images.githubusercontent.com/5074763/83269164-b4df8280-a194-11ea-8f54-f9a38ecb399e.png">
It's working as expected for me—adding `sx={{ resize: 'VALUE' }}` renders that to its CSS just as usual. The component doesn't have a special prop for it since it's standard CSS. Is there something else you were expecting?

**Comment by madebyankur** [comment]
It seems to be working indeed but I tried this yesterday and it wasn't working, not sure why.

Looks good! Thank you.
